# Generated by Django 3.2 on 2021-07-13 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_registered_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 9*********', regex='^(9)\\d{9}$')]),
        ),
    ]
