# Generated by Django 3.2.3 on 2021-07-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_registered_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='wifipassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
